### PR TITLE
Adding dellemc_pmax_movevolumes.py, dellemc_pmax_removecascadedsg.py and Ansible Custom filters

### PR DESCRIPTION
**Pull request by jbrt**
# Adding 2 new modules

- dellemc_pmax_movevolumes.py : Move TDEV from a SG to another
- dellemc_pmax_removecascadedsg.py : Remove a child SG from a parent SG

### CODE REVIEW

**Comment by jbrt** [comment]
Hi paul,

I've updated this PR with adding some Ansible custom filters i've made recently. These filters let you to manipulate easily WWN string (useful when you write PlayBooks with some WWN vars_prompt variables in various formats).

Here is an example (wwn_filters.yml):

```bash
$ ansible-playbook wwn_filters.yml
 
PLAY [Testing the WWN custom filters] ***********************************************************************************************************************************************************
 
TASK [Gathering Facts] **************************************************************************************************************************************************************************
ok: [localhost]
 
TASK [WWN lowercase with colons] ****************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "11:22:33:44:aa:bb:cc:dd"
}
 
TASK [WWN lowercase without colons] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "11223344aabbccdd"
}
 
TASK [WWN uppercase with colons] ****************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "11:22:33:44:AA:BB:CC:DD"
}
 
TASK [WWN uppercase without colons] *************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "11223344AABBCCDD"
}
 
PLAY RECAP **************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0
```

**Comment by rawstorage** [comment]
Julien,
have just wondering if you've seen the updated cascadedsg module in the development branch

- name: "Provision a new storage group"
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml

  tasks:
    - name: "Create New Storage Group volumes"
      dellemc_pmax_cascadedsg:
        array_id: "{{array_id}}"
        password: "{{password}}"
        unispherehost: "{{unispherehost}}"
        universion: "{{universion}}"
        user: "{{user}}"
        verifycert: "{{verifycert}}"
        parent_sg: ansible_parent
        child_sg_list:
        - ansible_child1
        - ansible_child2
        parent_state: present
        child_state: present
    - debug: var=storagegroup_detail

The child state variable can manipulate the adding and removing of children.  wondering if this would meet your needs.   I'll have a look at the filters, but this looks inline with some of what I had planned to do.  Let me know if the cascaded one meets your needs.  I'll test the other one and see if it works in my environment and do the merge once tested.

**Comment by jbrt** [comment]
Hello Paul,

You're right i haven't seen the modified version in the development branch. I'll see if I can swap this one directly into my code/playbooks.

For your information, we've plan to push you a new module called add_host_to_hostgroup.py soon.
And few days after some modules giving the ability to delete TDEVs.

On your side, do you have plan to change your actual modules a lot ? I mean, maybe we can exchange our "roadmaps" to avoid to do the same module on both sides. 

Regards,

**Comment by rawstorage** [comment]
Julien,
The cluster module has been modified to be more idempotent too..  Would be good to have a sync up on what you need.  I can setup a call if you would like to have a conversation in person on some of this and go through plans and current functionality..  My main aim is to keep the modules as generic and idempotent as possible.    Below is the functionality on this one.  I had thought about renaming some of the playbook variables if they don't immediately make sense to customers.  

I've a kanban setup on the project board for this project.  https://github.com/users/rawstorage/projects/

Below is the newer format for the cluster and all capabilities

tasks:
  - name: Create Cluster
    dellemc_pmax_cluster:
        - varsfiles:
            var.yml
        host_list:
        - AnsibleHost1
        - AnsibleHost2
        state: present
        host_state: in_cluster
  - name: Remove Host From Cluster
    dellemc_pmax_cluster:
        - varsfiles:
            var.yml
        host_list:
        - AnsibleHost1
        state: present
        host_state: not_in_cluster
  - name: Add Host to Cluster
    dellemc_pmax_cluster:
        - varsfiles:
            var.yml
        host_list:
        - AnsibleHost2
        state: present
        host_state: in_cluster
  - name: Delete Cluster
    dellemc_pmax_cluster:
        - varsfiles:
            var.yml
        host_list:
        - AnsibleHost2
        state: absent
        host_state: in_cluster

**Comment by jbrt** [comment]
Hi,

I share exactly the same point of view. 
I'll send you a mail to discuss some points with you.

Julien

**Comment by rawstorage** [comment]
Julien,  
I've merged this one for now, I think the move volume could potentially be handled in the volume module.  I'd like to try to keep functionality to as few modules as possible.  I will review again and come back to you on this one.

**Pull request merged**
