### PR TITLE
Modifying dellemc_pmax_host.py to accept host_flags as input

### PR DESCRIPTION
**Pull request by jbrt**
## Change log

- Adding documentation
- Adding host_flags on creation step (hosts flags and consistent_lun)
- Adding host_flag_dict on modify step (same thing)

Module tested on creation, modifying and deletion

### CODE REVIEW

**Comment by jbrt** [comment]
Paul,

Ok, it seems logic and more convinient for end-users, you're right.
So, here is what can i propose to you : 
- Adding a single boolean called 'consistent_lun' in the argument of the module
- Adding a new argument called 'host_type' (with a default value to 'default')
- Adding a dict as a constant value into the module containing all the differents OS flags (or just default, and hpux)
- Then, extract the flags from that structure

Is it Ok for you ?

**Comment by rawstorage** [comment]
This is perfect,  there should be ablity to disable consistent lun too, we should be able to turn it off.  But that's not high priority.. Turn it on when creating new Host is enough.  There may need to be additional checks in the hostgroup for consistent lun, if one host has it and the other doesn't I think we will get error adding to the hostgroup.  For now though this is enough.  HP-UX and Default is enough for me.  Default values cover everything except OpenVMS and HP-UX which are not high up on my radar for this project.

**Comment by jbrt** [comment]
Ok, we'll do the changes later this day or tomorrow.

Yeah, with Olivier we've talked about the ability for the users to switch off the consisten_lun but we think it can be a little bit tricky. I mean, since the IG is in production, with consistent_lun at True, for disabling this feature it means : 

- Going out each child IG 
- Putting the consistent_lun at ON on each of them and on the parent IG
- Go back to the initial situation

(We believe the is no way to do this "online", even with the latest VMAX but maybe we're wrong)
But, all of these operations are disruptive for the Masking View. So, maybe it can be dangerous to implement this feature or we have to find a way to well inform the customer of the impact of these manipulation.

But Ok, let's talk of that point for a later release.

**Comment by rawstorage** [comment]
Julien,
there is no way to turn on Consistent_LUN after ig has been added to a masking view but you can turn it off non-disruptively online.  Consistent_lun is not a high priority anymore no OS bar pre ESXI5.5 and HP-UX rely on lun address any more lun is identified by wwn or naaid..  Setting it to on is probably more out of habit for a lot of organisations these day.  Be interested in why you still use it.

**Comment by jbrt** [comment]
Paul,
Yes, you're right it's only used in some very specific usecase. 
For example, if you use a VM with disks pass trought RDM (Raw Device Mapping) if this VM is not seen on each ESX of your cluster with exactly the same LUN ID for each VMDK, operations like Storage VMotion doesn't works anymore.
That's why certain company still use this practice (event if it's become rare to still have VM using RDM).

**Comment by rawstorage** [comment]
Julien, this restriction was lifted with ESXi5.5.  RDM no longer is affected by vmotion if lun id doesn't match.  

https://cormachogan.com/2013/12/11/vsphere-5-5-storage-enhancement-part-7-lun-idrdm-restriction-lifted/

I was wondering if you were using for anther reason.. There is no harm setting or not these days for the majority of cases.

Thanks for getting back.

**Comment by jbrt** [comment]
Paul,
This is a very good news, we missed this feature to be honest. 
I've ask the question to our VMWare team if we still have ESXi < 5.5. If not, I think we will plan to stop the usage of the consitent_lun soon.

**Comment by jbrt** [comment]
## Updating PR with

- Adding host_type and consistent_lun as module variables
- Using "Format" function for all variable substitution in strings
- Refactoring the logic
- Members variables as switched to private
- Non public method switched to private
- Updating the unitest Playbook with more tests (and testing idempotent behavior)

**Comment by rawstorage** [comment]
Julien, I've merged your changes locally and run successfully, I'll do a push from my side to resolve the conflicts.  I made one small change to make the default host line 260

host_type=dict(type='str', required=False, default='default'),

If we call it default then we should set.  Other than that everything looks perfect.  Works fine in my environment

**Pull request closed without merging**
