### PR TITLE
Refactoring and adding renaming feature to dellemc_pmax_portgroup.py

### PR DESCRIPTION
**Pull request by jbrt**
## Changelog

- Global refactoring to stay consistent with other modules
- Adding renaming feature to dellemc_pmax_portgroup.py

### CODE REVIEW

**Comment by rawstorage** [comment]
Julien, tried to run this, Unit test looked like it was successful but seems remove ports task is not working, can you take a look again.

**Comment by rawstorage** [comment]
Julien, tried to run this, Unit test looked like it was successful but seems remove ports task is not working, can you take a look again.

**Comment by jbrt** [comment]
Paul,

I'll check that and I go back to you as soon as I found the problem.

**Comment by jbrt** [comment]
I've reran the unitest and I jave the same problem here. I try to understand why.

**Comment by jbrt** [comment]
@rawstorage 

I've found the problem: I've introduce a bug while refactoring of the code. 
I've changing the way how we parse the portId (regarding the inconsistency of the API on the formating of port IDs). Can you check at line 393 and tell me if this solution looks good for you ?

**Comment by rawstorage** [comment]
This looks good, however when we run the remove port the message is "No Changes made. Already in that state." and Change is made, I think this bug has been in for a bit.

**Comment by rawstorage** [comment]
Changed line 474 to 

        if not self._changed:
            self._message.append("No Changes made. Already in that state.")

This fixes this issue

**Comment by rawstorage** [comment]
I will merge this change and make change to correct message

**Pull request merged**
