### PR TITLE
dellemc_pmax_volume.py : Convert cap_gb to float

### PR DESCRIPTION
**Pull request by ocarm**
## Changelog
convert cap_gb to float in case the value is filled using var_prompts

### CODE REVIEW

**Comment by rawstorage** [comment]
Olivier,  CAP_GB ìs ok as a string as long as it can be converted to integer.

if you try to create 1.25 GB volume you will get error.. Not sure of the relevance of this change.  Also can you examine the location of the imports for the Anisble module, these import statements should follow the return docstring otherwise they are not valid for upstream.

**Comment by ocarm** [comment]
I 've done that because when i have filled cap_gb using var_prompts, i always got this error message :
 TypeError: '<' not supported between instances of 'float' and 'str'

In vmax rest api, volume_size or cap_gb are float. With unisphere 9.0 you are allowed to resize or create a volume using a float number like 1.25 GB  if you want to.

 I will change the location of docstrings.

**Comment by rawstorage** [comment]
Olivier.  Apologies, was looking at the SG only accepts integer but resize on volume accepts float.  I'll run and see if I can merge

**Comment by rawstorage** [comment]
Tested in Dell EMC Lab and all working.

**Pull request merged**
