### PR TITLE
Feature/dellemc pmax portgroup.py

### PR DESCRIPTION
**Pull request by ocarm**
## Change log
- array_ports is no longer needed to delete a port group.
- Refactoring code. 
 Try to reduce size of _create_and_modify_portgroup.
  Add multiples checks.

### CODE REVIEW

**Comment by rawstorage** [comment]
Olivier, 
I am getting errors running in my environment..
TASK [Create New Port Group and add ports] ******************************************************************************************************************
task path: /mnt/c/Users/martip5/PycharmProjects/dellemcpmax_ansible/unit_tests/portgroup_module_unit_tests.yml:17
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: martip5
<127.0.0.1> EXEC /bin/sh -c 'echo ~martip5 && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/martip5/.ansible/tmp/ansible-tmp-1554114894.91-117303700127228 `" && echo ansible-tmp-1554114894.91-117303700127228="` echo /home/martip5/.ansible/tmp/ansible-tmp-1554114894.91-117303700127228 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/storage/dellemc/dellemc_pmax_portgroup.py
<127.0.0.1> PUT /home/martip5/.ansible/tmp/ansible-local-1279so7ZMH/tmpVNQaDn TO /home/martip5/.ansible/tmp/ansible-tmp-1554114894.91-117303700127228/AnsiballZ_dellemc_pmax_portgroup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/martip5/.ansible/tmp/ansible-tmp-1554114894.91-117303700127228/ /home/martip5/.ansible/tmp/ansible-tmp-1554114894.91-117303700127228/AnsiballZ_dellemc_pmax_portgroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/martip5/.ansible/tmp/ansible-tmp-1554114894.91-117303700127228/AnsiballZ_dellemc_pmax_portgroup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/martip5/.ansible/tmp/ansible-tmp-1554114894.91-117303700127228/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "array_id": "000197900111",
            "array_ports": [
                "FA-1D:6",
                "FA-2D:6"
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port_state": "in_pg",
            "portgroup_id": "Ansible_PG",
            "state": "present",
            "unispherehost": "XXXXXXX",  <<Blanked my IP 
            "universion": 90,
            "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "verifycert": false
        }
    },
    "msg": "some port are not found on the array. check input ['FA-1D:6', 'FA-2D:6']."
}
        to retry, use: --limit @/mnt/c/Users/martip5/PycharmProjects/dellemcpmax_ansible/unit_tests/portgroup_module_unit_tests.retry

PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

When I run same playbook with original module it passes.

**Comment by ocarm** [comment]
Sorry for the inconvenience. I have rerun test in my environment and i have no issue. I will do more testing on an array with more FA ports.

**Comment by ocarm** [comment]
status report : I've done more tests on a bigger array with no problem.  I use python3 maybe the problem is here.

**Comment by rawstorage** [comment]
I’ll retry.

Paul Martin
Senior Principal Product Technologist
DellEMC | Enterprise Software and Storage - PowerMax and VMAX
•Office +353 21 4938979
Cell +35387 696 0621
Timezone GMT

Follow me on Twitter @rawstorage
Blog https://community.emc.com/people/PaulCork/blog/

Unisphere for VMAX REST API Information Hub<https://community.emc.com/docs/DOC-56447>

http://www.emc.com/collateral/faq/timefinder-snapvx-faqs.pdf
https://www.emc.com/collateral/technical-documentation/h13697-emc-vmax3-local-replication.pdf



[0_Specialist_Logo_-_Web,_PowerPoint,_Email][cid:image003.png@01CCA385.0F79A530]

Confidentiality Notice: This email message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential or proprietary information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, immediately contact the sender by reply e-mail and destroy all copies of the original message.

**Comment by rawstorage** [comment]
Olivier, if I output the list of valid array ports where this fails on my setup I see 

    "msg": [
        "12:DF-1C",
        "13:DF-1C",
        "16:DF-1C",
        "17:DF-1C",
        "12:DF-2C",
        "13:DF-2C",
        "16:DF-2C",
        "17:DF-2C",
        "6:FA-1D",
        "7:FA-1D",
        "32:FA-1D",
        "33:FA-1D",
        "34:FA-1D",
        "35:FA-1D",
        "36:FA-1D",
        "37:FA-1D",
        "38:FA-1D",
        "6:FA-2D",
        "7:FA-2D",
        "32:FA-2D",
        "33:FA-2D",
        "34:FA-2D",
        "35:FA-2D",
        "36:FA-2D",
        "37:FA-2D",
        "38:FA-2D",
        "24:SE-1E",
        "25:SE-1E",
        "26:SE-1E",
        "27:SE-1E",
        "24:SE-2E",
        "25:SE-2E",
        "26:SE-2E",
        "27:SE-2E",
        "4:RF-1F",
        "5:RF-1F",
        "4:RF-2F",
        "5:RF-2F"
    ]
}

the array ports are     "msg": [
        "FA-1D:6",
        "FA-2D:6"
    ]
}

looks like the logic in line 322 is appending the director to the port and not the other way so the subset from ports_list will never create a join.

**Comment by ocarm** [comment]
Thanks for debug. I was lucky,  i dont have this problem on my setup. I have an idea to secure it. 
Can you confirm that 9.1 rest API stills returns data with this format  ?
https://XX.XX.XX.XXX:8443/univmax/restapi/90/sloprovisioning/symmetrix/0002978xxxxx/port
  "symmetrixPortKey": [
    {
      "directorId": "DF-1C",
      "portId": "12"
    },
    {
      "directorId": "DF-1C",
      "portId": "13"
    },
    {
      "directorId": "DF-2C",
      "portId": "12"
    },

**Comment by rawstorage** [comment]
yes this format will not change between versions.  

I know sets is more efficient but when I built the orignial modules I used 2 dictionaries and compared those, this worked pretty well. I also had a bug fix in there to account for incorrect key data being returned on some systems. PortId was being returned in the format FA11D:6 instead of just the 6

        elif self.module.params['portgroup_id'] in pg_list:
            # check if port list supplied matches with what is in the group.
            # Building 2 dictionaries with same keys to compare
            ansible_ports_list = []
            for i in self.module.params['array_ports']:
                directorid, portid = i.split(":")
                ansible_ports_list.append({'directorId': directorid,
                                           'portId': portid})
            array_pg_ports_list = []
            array_pg_ports = self.conn.provisioning.get_portgroup(
                portgroup_id=self.module.params[
                    'portgroup_id'])["symmetrixPortKey"]
            # normalise array_pg dictionary list to match expected, Bugfix until
            #  9.1
            for i in array_pg_ports:
                try:
                    split = i['portId'].split(':')
                    i['portId'] = split[1]
                except IndexError:
                    pass
                array_pg_ports_list.append(i)

**Comment by ocarm** [comment]
I have pushed a new version.  I've also taken into account your bugfix.

**Comment by rawstorage** [comment]
This worked, I need to make a few small changes specifically around the ansible imports and trailing whitespace, these need to follow the documentation string.  This is a requirement for upstream ansible.  I will merge on my branch and update your changes.

**Pull request closed without merging**
