### PR TITLE
Fixing a bug when invalid number of new volumes to create is passed

### PR DESCRIPTION
**Pull request by jbrt**
## Changelog

- Fixing a bug when invalid number of new volumes to create is passed

### CODE REVIEW

**Comment by rawstorage** [comment]
I'll look at this one tomorrow Julien.  I'm on training this week but will have time first thing to take a look.

**Comment by rawstorage** [comment]
Apologies Julien, just got round to testing this, the change seems to create storage group with a default of no compression which is the opposite behavior from what we expect.  I re-tested a few times and went back to previous version using no_compression and this works, seems there is a bug since flipping no_compression parameter to compression again.

**Comment by rawstorage** [comment]
Julien,
I am on vacation for next 2 weeks, I'll look at this as soo. As I get back.



Excuse typos send from a mobile device. Sometimes autocorrect gets a bit creative without the knowledge of the sender


-------- Original message --------

**Comment by jbrt** [comment]
Hi Paul,

Have great vacations :-).
See you soon.

Julien

Le lun. 17 juin 2019 à 17:47, Paul Martin <notifications@github.com> a
écrit :

**Comment by jbrt** [comment]
Hi again @rawstorage 

I've done the needed changes: now when compression boolean value is changed, the related SG is switch to the right compression state.
Seems good now.

Regards,

**Pull request merged**
